import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portail-petitionnaire-cgdd.i-psfr.com/#/auth/lautorite-environnementale');
  await page.getByRole('button', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).fill('nchanti478@gmail.com');
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Blablabla40@');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('link', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('link', { name: 'FAIRE UNE DEMANDE' }).click();
  await page.getByText('Personne morale *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Saisine de l’autorité').click();
  await page.getByText('Cas par cas ad’hoc pour une UTN *').dblclick();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('*').nth(1).click();
  await page.getByText('Non *').nth(1).click();
  await page.getByText('Oui *').nth(1).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Auvergne-Rhône-Alpes' }).click();
  await page.getByRole('option', { name: 'Auvergne-Rhône-Alpes' }).click();
  await page.getByRole('option', { name: 'Bourgogne-Franche-Comté' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Auvergne-Rhône-Alpes' }).click();
  await page.getByRole('button', { name: 'Valider' }).click();
  await page.getByLabel('Remplir le formulaire').getByRole('button', { name: 'Valider' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).fill('WKF-3.4');
  await page.getByRole('textbox', { name: 'Numéro SIRET *' }).click();
  await page.getByRole('textbox', { name: 'Numéro SIRET *' }).fill('35600000000048');
  await page.locator('#ei1rf1l-emailPersonneMorale').click();
  await page.locator('#ei1rf1l-emailPersonneMorale').fill('a@a.com');
  await page.locator('#ejf8af-Prenom').click();
  await page.locator('#ejf8af-Prenom').fill('a');
  await page.locator('#es330go-nom').click();
  await page.locator('#es330go-nom').fill('a');
  await page.locator('#efgb3jte-NomPrenomEtQualiteDeLaPersonnePhysiqueHabiliteeARepresenterLaPersonnePubliqueResponsable').click();
  await page.locator('#efgb3jte-NomPrenomEtQualiteDeLaPersonnePhysiqueHabiliteeARepresenterLaPersonnePubliqueResponsable').fill('a');
  await page.locator('#eos8uas-PrenompersonnePhysResource').click();
  await page.locator('#efgb3jte-NomPrenomEtQualiteDeLaPersonnePhysiqueHabiliteeARepresenterLaPersonnePubliqueResponsable').fill('aa');
  await page.locator('#eos8uas-PrenompersonnePhysResource').fill('a');
  await page.locator('#exnsjle-nompersonnePhysResource').click();
  await page.locator('#exnsjle-nompersonnePhysResource').fill('a');
  await page.locator('#eaw5qel-QualitypersonnePhysResource').click();
  await page.locator('#eaw5qel-QualitypersonnePhysResource').fill('a');
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).click();
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).fill('06 66 66 66 66_');
  await page.locator('#es59zab-emailPersonneMoralesddc').click();
  await page.locator('#es59zab-emailPersonneMoralesddc').fill('a@a.com');
  await page.getByText('Exp: 20 Rue Lecourbe 75015 ParisSupprimer').click();
  await page.getByRole('textbox', { name: 'Exp: 20 Rue Lecourbe 75015' }).press('Dead');
  await page.getByRole('textbox', { name: 'Exp: 20 Rue Lecourbe 75015' }).press('^p');
  await page.getByRole('textbox', { name: 'Exp: 20 Rue Lecourbe 75015' }).fill('paris');
  await page.getByRole('option', { name: 'Paris', exact: true }).click();
  await page.locator('#eti19z4 > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'Structurante' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de l\'UTN *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de l\'UTN *' }).fill('WKF-3.4');
  await page.locator('#el6nolo > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'Manuelle' }).click();
  await page.getByText('Exp: ParisExp: ParisRemove').click();
  await page.getByRole('textbox', { name: 'Exp: Paris' }).fill('paris');
  await page.getByText('Paris : 75 Paris').click();
  await page.getByRole('textbox', { name: '2.5 Secteurs du territoire' }).click();
  await page.getByRole('textbox', { name: '2.5 Secteurs du territoire' }).fill('a');
  await page.getByLabel('3.1.1. Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.2 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.3 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.4 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.5 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.2.1. L’UTN a fait l’objet d').getByText('Non', { exact: true }).click();
  await page.locator('#e825toj > .choices > .form-control.ui').click();
  await page.getByText('R122-8/2- Les liaisons entre').click();
  await page.getByText('R122-8/2- Les liaisons entre domaines skiables alpins existantsSupprimer').click();
  await page.getByRole('option', { name: 'R122-8/2- Les liaisons entre' }).click();
  await page.getByRole('textbox', { name: '4.2.0. Caractéristiques' }).click();
  await page.getByRole('textbox', { name: '4.2.0. Caractéristiques' }).fill('a');
  await page.locator('#e6jylvc > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.getByRole('textbox', { name: '4.2.2. A quelle demande de dé' }).click();
  await page.getByRole('textbox', { name: '4.2.2. A quelle demande de dé' }).fill('a');
  await page.getByRole('textbox', { name: '4.2.3. Préciser les modes d\'' }).click();
  await page.getByRole('textbox', { name: '4.2.3. Préciser les modes d\'' }).fill('a');
  await page.getByRole('textbox', { name: '4.2.4. Préciser les risques' }).click();
  await page.getByRole('textbox', { name: '4.2.4. Préciser les risques' }).fill('a');
  await page.getByRole('textbox', { name: '4.2.5. Préciser les mesures' }).click();
  await page.getByRole('textbox', { name: '4.2.5. Préciser les mesures' }).fill('a');
  await page.getByRole('textbox', { name: '4.2.6. Préciser les' }).click();
  await page.getByRole('textbox', { name: '4.2.6. Préciser les' }).fill('a');
  await page.locator('#e72gfkp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('input[name="data[apikey54][e5yhsb5-e72gfkp]"]').nth(1).press('a');
  await page.locator('#e9px85 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eud7zf9 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eman1m > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e50rlr > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ea1j4xn > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eu8zf3f > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#egrefr5 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e7ohab8 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eayg12d > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e20n5lg > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eochwv > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#euo7azn > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#edtwr2f > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eqwqswt > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ezzro4h > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e7aqwzp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e3xpy7a > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e512dc > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eengso > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ejk9knd > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e4l4ra > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eqqvjba > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#elhhgwp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eu1vdtg > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ex9omwvo > div > .input-group > .form-control.input').click();
  await page.locator('.flatpickr-calendar.animate.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > span:nth-child(18)').click();
  await page.getByRole('textbox', { name: '7.2. Autres consultations' }).click();
  await page.getByRole('textbox', { name: '7.2. Autres consultations' }).fill('a');
  await page.locator('#e29fpxr > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ej7ulwf > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eqojc8q > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('.form-check-label.label-position-right.focus-style').click();
  await page.locator('.form-check-label.label-position-right.focus-style > span').click();
  await page.getByRole('button', { name: 'Page suivante   ' }).click();
  await page.getByRole('button', { name: '8.1.1 Dossier de révision,' }).setInputFiles('SPRINT3-EVO-QA(1).xlsx');
  await page.getByRole('button', { name: '8.1.2 Documents graphiques' }).setInputFiles('SPRINT3-EVO-QA.xlsx');
  await page.getByRole('button', { name: '8.1.3 L\'auto-évaluation (' }).setInputFiles('ExcelFile-1780671216323.xlsx');
});