import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portail-petitionnaire-cgdd.i-psfr.com/#/auth/lautorite-environnementale');
  await page.getByRole('button', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).fill('nchanti478@gmail.com');
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Blablabla40@');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('link', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('link', { name: 'FAIRE UNE DEMANDE' }).click();
  await page.getByText('Personne morale *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Saisine de l’autorité').click();
  await page.getByText('Cas par cas ad’hoc pour un PLU ou PLUi *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Non *').click();
  await page.getByText('Oui *').nth(1).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Auvergne-Rhône-Alpes' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Bourgogne-Franche-Comté' }).click();
  await page.getByRole('button', { name: 'Valider' }).click();
  await page.getByLabel('Remplir le formulaire').getByRole('button', { name: 'Valider' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).fill('WKF-3.2');
  await page.getByRole('textbox', { name: 'Numéro SIRET *' }).click();
  await page.getByRole('textbox', { name: 'Numéro SIRET *' }).fill('35600000000048');
  await page.locator('#eypnaa-emailPersonneMorale').click();
  await page.locator('#eypnaa-emailPersonneMorale').fill('a@a.com');
  await page.locator('#ejcbqt-nom').click();
  await page.locator('#ejcbqt-nom').fill('a');
  await page.locator('input[name="data[container88a][Prenom]"]').click();
  await page.locator('input[name="data[container88a][Prenom]"]').fill('a');
  await page.locator('#emffvk-qualitePersPhysHabilite').click();
  await page.locator('#emffvk-qualitePersPhysHabilite').fill('a');
  await page.locator('#eule5pm-nompersonnePhysResource').click();
  await page.locator('#emffvk-qualitePersPhysHabilite').fill('aa');
  await page.locator('#eule5pm-nompersonnePhysResource').fill('a');
  await page.locator('#enaziff-PrenompersonnePhysResource').click();
  await page.locator('#enaziff-PrenompersonnePhysResource').fill('a');
  await page.getByText('Exp: 20 Rue Lecourbe 75015 ParisSupprimer').click();
  await page.getByRole('textbox', { name: 'Exp: 20 Rue Lecourbe 75015' }).fill('paris');
  await page.getByRole('option', { name: 'Paris', exact: true }).click();
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).click();
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).fill('06 66 66 66 666');
  await page.locator('#ekpbrud-emailPersonneMoralesddc').click();
  await page.locator('#ekpbrud-emailPersonneMoralesddc').fill('a@a.com');
  await page.locator('#eqhzu4a-QualitypersonnePhysResource').click();
  await page.locator('#eqhzu4a-QualitypersonnePhysResource').fill('a');
  await page.locator('#e9jxx0r > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'PLU', exact: true }).click();
  await page.getByRole('textbox', { name: 'Intitulé du document *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé du document *' }).fill('WKF-3.2');
  await page.locator('#enajqei > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'Manuelle' }).click();
  await page.getByText('Exp: ParisRemove item').click();
  await page.getByRole('textbox', { name: 'Exp: Paris' }).fill('paris');
  await page.getByText('Paris : 75 Paris').click();
  await page.getByLabel('3.1.1 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.2 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.3 Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.2.1 Le PLU a fait l’objet d').getByText('Non').click();
  await page.locator('#e4h6pwo > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'Révision' }).click();
  await page.getByRole('textbox', { name: '4.2.1 Population concernée d\'' }).click();
  await page.getByRole('textbox', { name: '4.2.1 Population concernée d\'' }).fill('1');
  await page.locator('#ekrp9rq-ZoneUPresent').click();
  await page.locator('#ekrp9rq-ZoneUPresent').fill('1');
  await page.locator('input[name="data[PurcentActU]"]').click();
  await page.locator('#ekrp9rq-ZoneUPresent').fill('11');
  await page.locator('input[name="data[PurcentActU]"]').fill('1');
  await page.locator('#ededm7u-Zone1AUPresent').click();
  await page.locator('#ededm7u-Zone1AUPresent').fill('1');
  await page.locator('input[name="data[Purcent1AUctU]"]').click();
  await page.locator('input[name="data[Purcent1AUctU]"]').fill('1');
  await page.locator('#eqx4mpp-Zone2AUPresent').click();
  await page.locator('#eqx4mpp-Zone2AUPresent').fill('1');
  await page.locator('#esmkthg-ZoneAPresent').click();
  await page.locator('#esmkthg-ZoneAPresent').fill('1');
  await page.locator('#eppud17-ZoneNPresent').click();
  await page.locator('#eppud17-ZoneNPresent').fill('1');
  await page.locator('input[name="data[Purcent2AUctU]"]').click();
  await page.locator('input[name="data[Purcent2AUctU]"]').fill('1');
  await page.locator('input[name="data[PurcentActA]"]').click();
  await page.locator('input[name="data[PurcentActA]"]').fill('1');
  await page.locator('input[name="data[PurcentActN]"]').click();
  await page.locator('input[name="data[PurcentActN]"]').fill('1');
  await page.locator('#elsgi5-ZoneUAfter').click();
  await page.locator('#elsgi5-ZoneUAfter').fill('1');
  await page.locator('input[name="data[Zone1AUAfter]"]').click();
  await page.locator('input[name="data[Zone1AUAfter]"]').fill('1');
  await page.locator('#edtsuh-Zone2AUAfter').click();
  await page.locator('#edtsuh-Zone2AUAfter').fill('1');
  await page.locator('input[name="data[ZoneAAfter]"]').click();
  await page.locator('input[name="data[ZoneAAfter]"]').fill('1');
  await page.locator('#eeaso36-ZoneNAfter').click();
  await page.locator('#eeaso36-ZoneNAfter').fill('1');
  await page.locator('input[name="data[PersentUAfter]"]').click();
  await page.locator('input[name="data[PersentUAfter]"]').fill('1');
  await page.locator('input[name="data[Persent1AUAfter]"]').click();
  await page.locator('input[name="data[Persent1AUAfter]"]').fill('1');
  await page.locator('#ewxrhcr-Persent2AUAfter').click();
  await page.locator('#ewxrhcr-Persent2AUAfter').fill('1');
  await page.locator('#eet7ac-PersentAAfter').click();
  await page.locator('#eet7ac-PersentAAfter').fill('1');
  await page.locator('#enbzx92-PersentNAfter').click();
  await page.locator('#enbzx92-PersentNAfter').fill('1');
  await page.getByRole('textbox', { name: '4.2.3 Rappel des objectifs' }).click();
  await page.getByRole('textbox', { name: '4.2.3 Rappel des objectifs' }).fill('a');
  await page.getByRole('textbox', { name: '4.3.1 Contenu et objectifs de' }).click();
  await page.getByRole('textbox', { name: '4.3.1 Contenu et objectifs de' }).fill('a');
  await page.getByLabel('4.3.2 La procédure a pour').getByText('Non', { exact: true }).click();
  await page.getByLabel('4.3.3 Les incidences sur l’').getByText('Non', { exact: true }).click();
  await page.locator('#eegazp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e00uebm > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#em6o9yl > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e464sem > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e96el2s > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e1lpo56 > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.locator('#eo7viex > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ec1snuc > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ejbn2x > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#enu4mvc > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ebjc2s > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ee83ch > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ekhlof > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eri2rid > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ea191zc > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eioha67 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e1gdxz9 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e5nxgaf > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e4h98te > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#elbthx9 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e4ntgt9 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ejxxr1 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e7j2j0k > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ehfcce > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#exkb708 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ey95w2 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#elmv05 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eizqums > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ey0fma > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e7z8l8e > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e2tas6f > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ecyp90m > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#egc6rxi > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#esuu1s > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e55kpgo > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#elfer9 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ehcoova > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eqkkegw > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eyzpvq8 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ezb48tb > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e3vjjkf > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#en0rm0g > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ej34h2f > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e2d3kb > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e5m7xn > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e7q92hg > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eka0qlp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#er8ypmk > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e4m79f4 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#evu4p9d > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#elabkl > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#enjjhp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#edmp5i > div > .input-group > .form-control.input').click();
  await page.locator('.flatpickr-calendar.animate.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > span:nth-child(18)').click();
  await page.locator('#eym2hu > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ertmz3 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eohpsxd > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.getByRole('button', { name: 'Page suivante   ' }).click();
  await page.getByRole('button', { name: '8.1 Dossier de révision,' }).setInputFiles('ExcelFile-1780669103674.xlsx');
  await page.getByRole('button', { name: '8.2.1 Documents graphiques' }).setInputFiles('ExcelFile-1780649926195.xlsx');
  await page.getByRole('button', { name: 'L\'auto-évaluation (rubrique 6) *' }).setInputFiles('ExcelFile-1780927716327.xlsx');
});