import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portail-petitionnaire-cgdd.i-psfr.com/#/auth/lautorite-environnementale');
  await page.getByRole('button', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).fill('nchanti478@gmail.com');
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Blablabla40@');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('link', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('link', { name: 'FAIRE UNE DEMANDE' }).click();
  await page.getByText('Personne morale *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Saisine de l’autorité').click();
  await page.getByText('Cas par cas ad’hoc pour une carte communale *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Non *').click();
  await page.getByText('Oui *').nth(1).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Auvergne-Rhône-Alpes' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Bourgogne-Franche-Comté' }).click();
  await page.getByRole('button', { name: 'Valider' }).click();
  await page.getByLabel('Remplir le formulaire').getByRole('button', { name: 'Valider' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).fill('WKF-3.1');
  await page.getByRole('button', { name: '1.Identification de la' }).click();
  await page.getByRole('textbox', { name: 'Numéro SIRET  Renseignez le' }).click();
  await page.getByRole('textbox', { name: 'Numéro SIRET  *' }).fill('35600000000048');
  await page.getByRole('textbox', { name: 'Courriel : exemple@mail.fr *' }).fill('a@a.com');
  await page.getByRole('textbox', { name: 'Nom *', exact: true }).fill('a');
  await page.getByRole('textbox', { name: 'Prénom *' }).fill('a');
  await page.getByRole('textbox', { name: 'Qualité *' }).fill('a');
  await page.locator('#esk61bu-nompersonnePhysResource').fill('a');
  await page.locator('#e9x97ce-PrenompersonnePhysResource').fill('a');
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).fill('06 66 66 66 66_');
  await page.getByPlaceholder('exemple@exemple.com').fill('a@a.com');
  await page.locator('#e879nk-QualitypersonnePhysResource').fill('a');
  await page.getByRole('textbox', { name: 'Exp: 20 Rue Lecourbe 75015' }).fill('paris');
  await page.getByRole('textbox', { name: 'Intitulé du document *' }).fill('WKF-3.1');
  await page.getByRole('textbox', { name: 'Exp: Paris' }).fill('paris');
  await page.getByRole('textbox', { name: '4.2.1 Population concernée d\'' }).fill('1');
  await page.locator('#ewb6lm-ZoneUPresent').fill('1');
  await page.locator('input[name="data[PurcentActU]"]').fill('1');
  await page.locator('#ea06nvp-Zone1AUPresent').fill('1');
  await page.locator('input[name="data[Purcent1AUctU]"]').fill('1');
  await page.locator('#eqw932i-ZoneUAfter').fill('1');
  await page.locator('#el6mxhg-PersentUAfter').fill('1');
  await page.locator('input[name="data[Zone1AUAfter]"]').fill('1');
  await page.locator('#eaky1a-Persent1AUAfter').fill('1');
  await page.getByRole('textbox', { name: '4.3.1 Contenu et objectifs' }).fill('a');
  await page.getByRole('textbox', { name: '7.2 Autres consultations' }).fill('a');
  await page.getByRole('textbox', { name: 'Autre, préciser les modalités *' }).fill('a');
});