import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portail-petitionnaire-cgdd.i-psfr.com/#/auth/lautorite-environnementale');
  await page.getByRole('button', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).click();
  await page.getByRole('textbox', { name: 'Identifiant Format attendu:' }).fill('nchanti478@gmail.com');
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Blablabla40@');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('link', { name: 'Accéder à mon espace' }).click();
  await page.getByRole('link', { name: 'FAIRE UNE DEMANDE' }).click();
  await page.getByText('Personne morale *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Saisine de l’autorité').click();
  await page.getByText('Cas par cas ad’hoc pour un SCoT *').click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByText('Non *').click();
  await page.getByText('Oui *').nth(1).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Auvergne-Rhône-Alpes' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Bourgogne-Franche-Comté' }).click();
  await page.getByRole('button', { name: 'Valider' }).click();
  await page.getByLabel('Remplir le formulaire').getByRole('button', { name: 'Valider' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé de la demande *' }).fill('WKF-3.3');
  await page.getByRole('textbox', { name: 'Numéro SIRET *' }).click();
  await page.getByRole('textbox', { name: 'Numéro SIRET *' }).fill('35600000000048');
  await page.getByRole('textbox', { name: 'Courriel : exemple@mail.fr *' }).click();
  await page.getByRole('textbox', { name: 'Courriel : exemple@mail.fr *' }).fill('a@a.com');
  await page.locator('input[name="data[Prenom]"]').click();
  await page.locator('input[name="data[Prenom]"]').fill('a');
  await page.locator('input[name="data[nom]"]').click();
  await page.locator('input[name="data[nom]"]').fill('a');
  await page.locator('input[name="data[NomPrenomEtQualite]"]').click();
  await page.locator('input[name="data[NomPrenomEtQualite]"]').fill('a');
  await page.locator('#egidzn4-PrenompersonnePhysResource').click();
  await page.locator('#egidzn4-PrenompersonnePhysResource').fill('a');
  await page.locator('#e9l7hrn-nompersonnePhysResource').click();
  await page.locator('#e9l7hrn-nompersonnePhysResource').fill('a');
  await page.locator('#e1yzfd-QualitypersonnePhysResource').click();
  await page.locator('#e1yzfd-QualitypersonnePhysResource').fill('a');
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).click();
  await page.getByRole('textbox', { name: 'Téléphone : +XX X XX XX XX XX' }).fill('06 66 66 66 66_');
  await page.getByRole('textbox', { name: 'Courriel : exemple@mail.fr', exact: true }).click();
  await page.getByRole('textbox', { name: 'Courriel : exemple@mail.fr', exact: true }).fill('a@a.com');
  await page.getByText('Exp: 20 Rue Lecourbe 75015 ParisSupprimer').click();
  await page.getByRole('textbox', { name: 'Exp: 20 Rue Lecourbe 75015' }).fill('paris');
  await page.getByRole('option', { name: 'Paris', exact: true }).click();
  await page.getByRole('textbox', { name: 'Intitulé du document *' }).click();
  await page.getByRole('textbox', { name: 'Intitulé du document *' }).fill('WKF-3.3');
  await page.locator('.form-control.input').first().click();
  await page.locator('.flatpickr-calendar.animate.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > span:nth-child(18)').click();
  await page.locator('#e5i742w > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'Manuelle' }).click();
  await page.getByText('Exp: ParisRemove item').click();
  await page.getByRole('textbox', { name: 'Exp: Paris' }).fill('paris');
  await page.getByText('Paris : 75 Paris').click();
  await page.getByLabel('3.1.1. Le territoire est-il').getByText('Non').click();
  await page.getByLabel('3.1.2 Le territoire est-il').getByText('Non').click();
  await page.locator('#edo1h1w > div > .input-group > .form-control.input').click();
  await page.locator('.flatpickr-calendar.animate.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > span:nth-child(18)').click();
  await page.getByLabel('3.2.2. Cette évaluation').getByText('Non').click();
  await page.getByRole('textbox', { name: '3.2.3 Comment l’avis de l’' }).click();
  await page.getByRole('textbox', { name: '3.2.3 Comment l’avis de l’' }).fill('a');
  await page.getByLabel('3.2.4 Depuis l’évaluation').getByText('Non').click();
  await page.getByRole('button', { name: '4. Type de procédure engagée' }).click();
  await page.locator('#e9aw74 > .choices > .form-control.ui').click();
  await page.getByRole('option', { name: 'Révision' }).click();
  await page.getByRole('textbox', { name: '4.2.1. Population concernée d' }).click();
  await page.getByRole('textbox', { name: '4.2.1. Population concernée d' }).fill('1');
  await page.getByRole('textbox', { name: '4.2.2. Rappel des objectifs' }).click();
  await page.getByRole('textbox', { name: '4.2.2. Rappel des objectifs' }).fill('a');
  await page.getByRole('textbox', { name: '4.3.1. Contenu et objectifs' }).click();
  await page.getByRole('textbox', { name: '4.3.1. Contenu et objectifs' }).fill('a');
  await page.getByLabel('4.7.1. La procédure a-t-elle').getByText('Non').click();
  await page.getByRole('button', { name: '5. Sensibilité' }).click();
  await page.getByRole('button', { name: ' 5.1 Le SCoT est concerné par' }).click();
  await page.getByLabel('Les dispositions de la loi montagne').getByText('Non', { exact: true }).click();
  await page.locator('#e60t4ve > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e1zc6e > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e99nx7l > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#elunk5m > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#emdrmae > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e3ayu0k > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#erz4l4a > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ej318u > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#epw8lph > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ejisd6 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#est75cm > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#efrwcb6 > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.locator('#e3ayf1 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e65gdzq > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ed0td8 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e7j6sb > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ex0vhik > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#emrl9n > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ezg006m > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.getByRole('button', { name: '5.2. Le ou les secteurs qui' }).click();
  await page.locator('#edck922 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eel8lr4s > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e3z67jh > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e33vf3p > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e3r4a8 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e0g5wof > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eb2ubo > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e49d5f > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.getByRole('button', { name: '5.3. Le ou les secteurs qui' }).click();
  await page.locator('#ee2z9v > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e6hec6 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eoe509h > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#evomsu7 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#edjlrqd > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e53e9da > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eqgtacv > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eqgtacv > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.locator('.form-check-label.label-position-right.focus-style > span').click();
  await page.locator('#ep55n3 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#enlv7l > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ecjo1sn > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eelqdh3 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e9z6lx28 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#ejlly1 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eubjsj > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#eew1zv3 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.getByRole('button', { name: '5.4 Des constructions à usage' }).click();
  await page.locator('#empg9c9 > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.getByRole('button', { name: '7. Autres procédures' }).click();
  await page.locator('#exwq7m > div > .input-group > .form-control.input').click();
  await page.locator('.flatpickr-calendar.animate.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-days > .dayContainer > span:nth-child(18)').click();
  await page.getByRole('textbox', { name: '7.2 Autres consultations' }).click();
  await page.getByRole('textbox', { name: '7.2 Autres consultations' }).fill('a');
  await page.getByRole('button', { name: '7.3 Procédure de' }).click();
  await page.locator('#e21mhze > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#e114l9e > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('#etdfcxp > .form-radio > div:nth-child(2) > .form-check-label > span').click();
  await page.locator('.form-check-label.label-position-right.focus-style > span').click();
  await page.getByRole('button', { name: 'Page suivante   ' }).click();
  await page.getByRole('button', { name: '8.1 Dossier de révision,' }).setInputFiles('SPRINT3-EVO-QA(1).xlsx');
  await page.getByRole('button', { name: '8.1.2 Documents graphiques' }).setInputFiles('SPRINT3-EVO-QA.xlsx');
  await page.getByRole('button', { name: 'L\'auto-évaluation (rubrique 6) *' }).setInputFiles('ExcelFile-1780589612019.xlsx');
});